name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.24", "1.23", "1.22", "1.21"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # depends on go.sum
      - run: go mod tidy
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_go_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - if: ${{ matrix.go == '1.24' }}
        run: go get -u ./...
      - run: go generate ./ent && go mod tidy
      - run: go test -v
